### ISSUE TITLE
[Suggestion] Make falling tree hurt mobs like an anvil.

### ISSUE THREAD

**Issue by eoistana** [Shovinus/ChopDownUpdated#1]
It would be super fun, if you could chop trees and have them fall on mobs and squash them :)

**Comment by Shovinus** [comment]
I like the idea, will have to see could make the damage done configurable, otherwise killing withers might get a bit easy, though tbh I would love to see that.

**Comment by Shovinus** [comment]
Done in latest release (Not stated in change log as forgot, but it is there)
