### ISSUE TITLE
ChopDownUpdated does not work in 1.10.2

### ISSUE THREAD

**Issue by JaceySanders** [Shovinus/ChopDownUpdated#14]
I created a new 1.10.2 instance and added only the version appropriate ChopDownUpdated file. Breaking log blocks in trees does not cause the tree fall event. 

forge 12.18.3.2511
Java 8 Update 131

**Comment by Shovinus** [comment]
Ok, don't quite get that why no one reported yet until now, will have to check tomorrow, there is some other fixes I want to look at too anyway

**Comment by Shovinus** [comment]
Fixed, also found a fair few other issues, released to curse, just gotta wait for them to approve.
