### ISSUE TITLE
Falling blocks get stuck on fences and walls

### ISSUE THREAD

**Issue by Bulldog83** [Shovinus/ChopDownUpdated#15]
Minecraft 1.12.2
Forge 14.23.4.2705
CDU 1.1.0

When the blocks fall on the fence or the wall, they stays falling blocks.
![2018-07-11_10 30 06](https://user-images.githubusercontent.com/20737750/42558400-cc06f84e-84f9-11e8-83f9-fc9531ba2f11.png)
![2018-07-11_10 32 06](https://user-images.githubusercontent.com/20737750/42558401-cc28e706-84f9-11e8-926f-9205f5c06eb1.png)

**Comment by Shovinus** [comment]
yes, that is minecraft mate, it is just a falling entity, do the same with sand ...
