### ISSUE TITLE
Biomes O' Plenty Errors

### ISSUE THREAD

**Issue by UnlimatedStone9** [Shovinus/ChopDownUpdated#16]
Upon testing trees with this mod I noticed that BOP Origin Trees cannot be felled, Probably because they use Oak logs with unique leaves, If this is the case then all other BOP trees that use vanilla logs or other mod that use vanilla logs will not be affected

**Comment by UnlimatedStone9** [comment]
I Doubt you're going to add support for the bamboo trees though as they have a weird model but that'd be cool

**Comment by Shovinus** [comment]
Bamboo trees actually collapse on any lower block break, they are not logs, BOP handles that itself.
Can you turn on "\cdu showBlockNames" and click each log and leaf type? Mangrove will be one of the weird shaped trees that is hard to handle as it assumes it is multiple trees unfortunately.

**Comment by wenlfs** [comment]
Actually seems that a lot of trees are not working.

I solved some if you want to update.

Biomes O' plenty and one from Rustic

{"logs":["minecraft:log:0"],"leaves":["biomesoplenty:leaves_2:11","biomesoplenty:leaves_2:8","biomesoplenty:leaves_1:9","rustic:leaves_apple:0"]}
{"logs":["minecraft:log:2"],"leaves":["biomesoplenty:leaves_0:8"]}
{"logs":["minecraft:log:2:1"],"leaves":["biomesoplenty:leaves_0:9"]}
{"logs":["biomesoplenty:log_0:4"],"leaves":["biomesoplenty:leaves_3:11"]}
{"logs":["biomesoplenty:log_0:5"],"leaves":["biomesoplenty:leaves_2:9","biomesoplenty:leaves_2:10]}
{"logs":["biomesoplenty:log_0:6"],"leaves":["biomesoplenty:leaves_1:8"]}
{"logs":["biomesoplenty:log_0:7"],"leaves":["biomesoplenty:leaves_1:10"]}
{"logs":["biomesoplenty:log_1:5"],"leaves":["biomesoplenty:leaves_0:11"]}
{"logs":["biomesoplenty:log_1:6"],"leaves":["biomesoplenty:leaves_4:8"]}
{"logs":["biomesoplenty:log_2:4"],"leaves":["biomesoplenty:leaves_4:10"]}
{"logs":["biomesoplenty:log_2:5"],"leaves":["biomesoplenty:leaves_4:11"]}
{"logs":["biomesoplenty:log_2:6"],"leaves":["biomesoplenty:leaves_5:8"]}
{"logs":["biomesoplenty:log_2:7"],"leaves":["biomesoplenty:leaves_3:8"]}
{"logs":["biomesoplenty:log_3:4"],"leaves":["biomesoplenty:leaves_3:10"]}
{"logs":["biomesoplenty:log_3:5"],"leaves":["biomesoplenty:leaves_5:9"]}
{"logs":["biomesoplenty:log_3:6"],"leaves":["biomesoplenty:leaves_5:10"]}
{"logs":["biomesoplenty:log_3:7"],"leaves":["biomesoplenty:leaves_5:11"]}

I tested and they were working but, please, test they too. Hope it help.
Thank you for the mod.

**Comment by Shovinus** [comment]
Fixed 56ca7c2d0841b585571a98382cafe0085605d32d
