### ISSUE TITLE
Tree log bouncing on walls

### ISSUE THREAD

**Issue by LemADEC** [Shovinus/ChopDownUpdated#18]
On MC1.12.2, as of version 1.1.0, we have a log bouncing endlessly over a wall instead of being placed:
https://i.gyazo.com/c394d68333a08544b9d3701e4edd7173.mp4
![image](https://user-images.githubusercontent.com/4776032/43370485-c3718e44-937f-11e8-93f9-28b5c080eb34.png)

**Comment by Shovinus** [comment]
It is a falling entity, all falling entities do this with walls unfortunately, try sand for example, I could try creating me own class but it likely be even worse

**Comment by LemADEC** [comment]
Why would it be worse?
what prevents us to derivate the FallingEntity class and add a time out that place the block at location?

**Comment by Shovinus** [comment]
it already has a timeout of sorts, but the time out is for once managed to place, I have left it in because ultimately, people  don't care about it for vanilla sand, why care for this XD

**Comment by LemADEC** [comment]
It's improbable for sand to fall on a wall.
It's much more probable for a tree to fall over your walls.

**Comment by Shovinus** [comment]
This is true.


________________________________

**Comment by Shovinus** [comment]
Feel free to patch it if you want, you look to know more about MC than me

**Comment by LemADEC** [comment]
You learn things by doing things you didn't know how to make first

**Comment by Shovinus** [comment]
Yeh but cba

**Comment by LemADEC** [comment]
cba?

**Comment by Shovinus** [comment]
I need to recreate the entire falling entity class because extending theirs does not give enough access to override.

**Comment by LemADEC** [comment]
Which accesses are missing?

**Comment by LemADEC** [comment]
You can add them to your AccessTransformer to change them to public or protected.
You could also access them by Reflexion, just be careful to only retrieve the Field instance once since the lookup is fairly slow.

**Comment by Shovinus** [comment]
No idea what accesstransformer is, I get reflection, but it is easier to just copy the code and edit anyway.

**Comment by LemADEC** [comment]
You lose compatibility and increase maintenance by duplicating the code.
https://tutorials.darkhax.net/tutorials/access_transformers/

**Comment by Shovinus** [comment]
Fixed, also fixed falling blocks popping off.
1a713f199330f8fa381c0a1b2c43b6ca3c407ce3
