### ISSUE TITLE
Yet another mod with odd trees: Terra

### ISSUE THREAD

**Issue by Zygus42** [Shovinus/ChopDownUpdated#2]
Terra is a world gen mod with biomes, and the trees in it such as white spruce do not get chopped down by this mod.

Another mod which also has issues is Tropicraft, which has palms which do not chop down - mind you, those also have leaves that do no decay and coconuts that do not fall down, so those trees might have other issues entirely.

**Comment by Shovinus** [comment]
can you link the 2 mods that need configuring?

**Comment by Zygus42** [comment]
https://minecraft.curseforge.com/projects/terra-biomes-stuff

https://minecraft.curseforge.com/projects/tropicraft

**Comment by Shovinus** [comment]
XD I am glad it came out though.

**Comment by Zygus42** [comment]
Heck yes !! Awesome mod.

**Comment by Zygus42** [comment]
Terra trees are still not chopping down with v1.09.

**Comment by Shovinus** [comment]
Is this 1.12 or 1.10/1.11?

**Comment by Shovinus** [comment]
Also did you delete the old config?

**Comment by Zygus42** [comment]
1.12.  You are indeed correct, deleting the old config file was the key.  Works as designed now.   Even though they both had config version 1.0.9 at the top - go figure.
