### ISSUE TITLE
Custom configuration deleted when config version changes

### ISSUE THREAD

**Issue by esotericist** [Shovinus/ChopDownUpdated#21]
It seems like every time `CONFIG_VERSION` changes, all of my custom configuration entries (in `ignoreTools` and `sharedLeaves`) are deleted rather than migrated, even though they're in the same configuration key and same format.

**Comment by esotericist** [comment]
Examples, in case that's somehow helpful:
```
    S:ignoreTools <
        tconstruct:lumberaxe:.*
        thaumcraft:elemental_axe:.*
        astralsorcery:chargedcrystalaxe:.*
        botania:terraaxe:.*
     >
```
```
    S:sharedLeaves <
        harvestcraft:beehive:0
        rustic:beehive:0
        forestry:beehives:0
        forestry:beehives:1
        forestry:beehives:2
        forestry:beehives:3
        forestry:beehives:4
        forestry:beehives:5
        forestry:beehives:6
        magicbees:hiveblock:0
        magicbees:hiveblock:1
        magicbees:hiveblock:2
        magicbees:hiveblock:3
        magicbees:hiveblock:4
        magicbees:hiveblock:5
     >
```

**Comment by Shovinus** [comment]
Yes, this is semi intentional behaviour, there was a lot of people that didn't realise they needed to clear the old config to get any new trees add and this caused issues so I opted for auto deleting each version change. Really I should make it save the old configs in a backup location somewhere.

**Comment by Shovinus** [comment]
9f0a77b
Fixed, how old config is backed up to old file
