### ISSUE TITLE
[Config] The Twilight Forest

### ISSUE THREAD

**Issue by Shovinus** [Shovinus/ChopDownUpdated#24]
https://minecraft.curseforge.com/projects/the-twilight-forest?gameCategorySlug=mc-mods&projectID=227639

**Comment by wenlfs** [comment]
I have add some Twilight Forest trees, let me share if it helps. The Twilight oak and Darkwood trees weren't add because they need tweaks.

```
{"logs":["twilightforest:twilight_log:0"],"leaves":["twilightforest:twilight_leaves:3"]}
{"logs":["twilightforest:twilight_log:1"],"leaves":["twilightforest:twilight_leaves:1"]}
{"logs":["twilightforest:twilight_log:2"],"leaves":["twilightforest:twilight_leaves:2"]}
{"logs":["twilightforest:magic_log:0","twilightforest:magic_log_core:0"],"leaves":["twilightforest:magic_leaves:0"]}
{"logs":["twilightforest:magic_log:1","twilightforest:magic_log_core:1"],"leaves":["twilightforest:magic_leaves:1"]}
{"logs":["twilightforest:magic_log:2","twilightforest:magic_log_core:2"],"leaves":["twilightforest:magic_leaves:2"]}
{"logs":["twilightforest:magic_log:3","twilightforest:magic_log_core:3"],"leaves":["twilightforest:magic_leaves:3"]}
```
These need tweaks:

To the Twilight oak adds `"twilightforest:twilight_leaves:0"` to `twilight_log:0`
To Darkwood `{"logs":["twilightforest:twilight_log:3"],"leaves":["twilightforest:dark_leaves:0"]}`

**Comment by wenlfs** [comment]
Also I have added some from The Erebus. The Marshwoods need tweaks and maybe you can find others.

```
{"logs":["erebus:log_baobab:0"],"leaves":["erebus:leaves_baobab:0"]}
{"logs":["erebus:log_eucalyptus:0"],"leaves":["erebus:leaves_eucalyptus:0"]}
{"logs":["erebus:log_mahogany:0"],"leaves":["erebus:leaves_mahogany:0"]}
{"logs":["erebus:log_mossbark:0"],"leaves":["erebus:leaves_mossbark:0"]}
{"logs":["erebus:log_asper:0"],"leaves":["erebus:leaves_asper:0"]}
{"logs":["erebus:log_cypress:0"],"leaves":["erebus:leaves_cypress:0"]}
{"logs":["erebus:log_marshwood:0"],"leaves":["erebus:leaves_marshwood:0"]}
{"logs":["erebus:log_balsam:0"],"leaves":["erebus:leaves_balsam:0"]}
```

**Comment by wenlfs** [comment]
I forgot the from [The Midnight](https://minecraft.curseforge.com/projects/the-midnight).

```
{"logs":["midnight:dark_willow_log:0"],"leaves":["midnight:dark_willow_leaves:0"]}
{"logs":["midnight:shadowroot_log:0"],"leaves":["midnight:shadowroot_leaves:0"]}
```

**Comment by Shovinus** [comment]
Have added betweenlands and some of twilight, but could not find the magic trees yet, where are they?

**Comment by wenlfs** [comment]
The magic trees are only find in dungeons, I believe that this haven't change. 
[Link to wiki](http://benimatic.com/tfwiki/index.php?title=Magic_Saplings)

**Comment by Shovinus** [comment]
https://docs.google.com/spreadsheets/d/1Z47faRIsptEdN57bWbTZk16pULWx7a1Rw-qIXQvaDWY/edit#gid=0
