### ISSUE TITLE
[Suggestion][Mod Support]Plants Nether Trees, and Natural Pledge, and Aether Legacy, and Abyssalcraft, 

### ISSUE THREAD

**Issue by TeetoKaziim** [Shovinus/ChopDownUpdated#28]
https://gist.github.com/TeetoKaziim/1360fabb5772e11c503dde94a73f6c4c

An excerpt from my own configs, some suggested additions for mods of varying degrees of popularity.
Notable: Apparently I missed the nether trees when submitting the Plants configs back in the day? Sorry about that.

**Comment by Shovinus** [comment]
Can you split this into each config so I can tick them off as I do them?

**Comment by TeetoKaziim** [comment]
Can do, I'll close this one and open seperate ones.
