### ISSUE TITLE
Forestry compat don't work

### ISSUE THREAD

**Issue by QuantumStatement** [Shovinus/ChopDownUpdated#29]
Minecraft 1.12.2
Forge 14.23.5.2768
Chop Down Updated 1.2.2
Forestry 5.8.2.374

For some reason Forestry compatability don't work. In config "Forestry" entry set to `true`

**Comment by Shovinus** [comment]
All? Or just a specific tree?

**Comment by QuantumStatement** [comment]
> All? Or just a specific tree?
All trees

**Comment by QuantumStatement** [comment]
Last working ChopDown Updated version is 1.1.0

**Comment by Shovinus** [comment]
It seems he has changed the name of his leaves from default to decorative recently

**Comment by QuantumStatement** [comment]
No, he don't
![2018-11-23_16 39 52](https://user-images.githubusercontent.com/35406698/48946455-dbd54c80-ef3e-11e8-9003-d32e749a94b6.png)
![2018-11-23_16 40 31](https://user-images.githubusercontent.com/35406698/48946457-dc6de300-ef3e-11e8-99b4-0bbada12226e.png)
You may get `decorative` leaves with shears or middle mouse button (in creative mode)

**Comment by Shovinus** [comment]
Yeh strange I wanted to test in eclipse with the forestry pack

**Comment by Shovinus** [comment]
I normally rely on showBlockName to tell me what it thinks the block is as it is the exact method the mod uses

**Comment by QuantumStatement** [comment]
Changing Forestry leaves to 'decorative' is working. I tested this on ChopDown Updated 1.2.0

**Comment by Shovinus** [comment]
I'm confused about this, because it's the same config :s

**Comment by Shovinus** [comment]
Thanks for testing, I've got loads of configs to update

**Comment by Shovinus** [comment]
something has changed for sure the old logs no longer seem to line up at all, see here :
https://docs.google.com/spreadsheets/d/1N0YyQcQMBpja6IkW9ATZBU7waebzEw16aHNIfi6mmpY/edit#gid=0
columns n and o are the configs I currently have for the trees an not the previous ones. I don't understand how 1.2.0 worked with forestry because the ids have all changed.

**Comment by QuantumStatement** [comment]
> how 1.2.0 worked with forestry

I manually change leaves IDs in config

**Comment by Shovinus** [comment]
ahhhh :) that makes sense

**Comment by Shovinus** [comment]
well I managed to map out them all but found issues with the tile entities so I need to look at the code again.

**Comment by QuantumStatement** [comment]
> but found issues with the tile entities

#7?
![2018-11-28_23 32 10](https://user-images.githubusercontent.com/35406698/49180701-79c57e80-f366-11e8-83a1-2491d3b0e03b.png)

**Comment by Shovinus** [comment]
yeh that

**Comment by Shovinus** [comment]
it is due to changes I made in how the blocks fall, obviously it is not also compensating for the tile entity data

**Comment by Shovinus** [comment]
fixed the tile issue  ad2746996e826c0303807e22633c23b4d85d7a4d
