### ISSUE TITLE
Minor issue with forestry

### ISSUE THREAD

**Issue by Zygus42** [Shovinus/ChopDownUpdated#3]
ChopDown+Updated+(1.12.2+)-1.0.5
forestry_1.12.2-5.8.0.270

The leaves of the Padauk tree stayed where they were instead of falling over:

![2018-04-22_23 03 33](https://user-images.githubusercontent.com/20757445/39096367-888912ca-4681-11e8-80e7-5a82c01a2382.png)

**Comment by Zygus42** [comment]
You're correct - if you spawn in a tree with a sapling from the creative menu, it falls over properly.  

BUT if you chop over any forestry tree that was prespawned into the world, then it doesn't.  

And the leaf values are different.  If you use it on the trees that you spawn, the value is: forestry:leaves:0 for both trees, even though they clearly look different and the one probe mod recognizes which is which.  On an already spawned sugar maple the value is: forestry:leaves:2:1.  On an already spawned hill cherry, the value is: forestry:leaves:1:2.  

The log values are the same between the spawned and pre-spawned.

I even analyzed one of the saplings from the creative inventory in their portable analyzer, but made no difference.  

Forestry have always done dodgy things with their trees - remember having issues with their wood and their leaves back in 1.6, 1.7, 1.8, 1.10 etc :)

**Comment by Zygus42** [comment]
hmmm, not sure why my ":leaves" were replaced with some weird icon.

**Comment by Shovinus** [comment]
bleh that sucks, that would mean finding all the trees after world gen and mapping them, I have raised an issue with the creator to see if he can give me the lists. I really don't want to spend a few hours looking for trees XD. 
If you want make a copy of this sheet and do changes:

https://docs.google.com/spreadsheets/d/1I54fRT9_TDye03vocR2ahYbpFHiTrS-ZVnsYOihWh78/edit?usp=sharing

the leaves need to be added after the corresponding logs.

**Comment by Shovinus** [comment]
16c999e8c71134401a78d4d46435517b2271d6ac
