### ISSUE TITLE
[Mod Compatibility]: Natural Pledge

### ISSUE THREAD

**Issue by TeetoKaziim** [Shovinus/ChopDownUpdated#31]
https://gist.github.com/TeetoKaziim/1360fabb5772e11c503dde94a73f6c4c

The files in the gist are labeled by the mod they correspond to. Of course, you can probably see the mod ID. I don't know why i'm typing seperate things.

**Comment by Shovinus** [comment]
Added : https://docs.google.com/spreadsheets/d/1hEDfqZKX4jsuCq2MATvJaB7C0JWcoX3Y55McxNsOOUY/edit#gid=0
