### ISSUE TITLE
[Mod Compatibility]: Aether Legacy

### ISSUE THREAD

**Issue by TeetoKaziim** [Shovinus/ChopDownUpdated#32]
https://gist.github.com/TeetoKaziim/1360fabb5772e11c503dde94a73f6c4c

This is the same gist as the other gist, the issues are seperate just so you can tick them off. It took me a solid like, minute to fully understand what you were asking me for. I'm not so smart some times, I really shoulda did it this way in the first place.

**Comment by Shovinus** [comment]
Already added in 1.2.2
