### ISSUE TITLE
[Mod Compat] Cuisine

### ISSUE THREAD

**Issue by yikies** [Shovinus/ChopDownUpdated#34]
{"logs":["cuisine:log"], "leaves":["cuisine:sheared_leaves:*"]}

i think thats right. still not really sure how the config is supposed to work, it always errored out for me

**Comment by Shovinus** [comment]
its regex, so :* would mean ":" 0 or more times, and would not match
"." in regex means any character so .* means anything goes for any number of characters basically

**Comment by yikies** [comment]
Ah, gotcha. I’ve also got another stupid question. Where do i actually put the config lines? There wasn’t an obvious place in the only config i could find (chopdownupdated.cfg). I tried pasting the config lines for Betweenlands and Twilight Forest directly from the google doc, but starting the game gives me an errored config and regenerates a new one.

**Comment by Shovinus** [comment]
can you paste your config?

**Comment by yikies** [comment]
https://hastebin.com/adibujotas.cpp

https://hastebin.com/velipubaho.cpp

after updating to the newest version with the new config I tried both of these, both do not work.

**Comment by Shovinus** [comment]
I can't open this site on my computer for some reason, can you try pastebin instead?

**Comment by QuantumStatement** [comment]
@yikies, first config should work fine, if you make some changes:
1. Log also should have metadata ( `cuisine:log:0` )
2. You shouldn't add leaves to `shared_leaves` config entry

**Comment by Shovinus** [comment]
this works fine :
 {"logs":["cuisine:log:0"], "leaves":["cuisine:sheared_leaves:.*"]}
I will add to the inbuilt options
