### ISSUE TITLE
Slight issue with Natura Redwoods

### ISSUE THREAD

**Issue by Zygus42** [Shovinus/ChopDownUpdated#8]
These are almost working - look magnificent when chopped down, but some balls of stuff left up in the sky at the very top.

![2018-05-08_23 44 33](https://user-images.githubusercontent.com/20757445/39767728-02b49a48-531a-11e8-9b09-82bafcce2d73.png)
![2018-05-08_23 44 23](https://user-images.githubusercontent.com/20757445/39767730-042e9572-531a-11e8-8ea9-deba124371bc.png)
![2018-05-08_23 44 41](https://user-images.githubusercontent.com/20757445/39767732-054b98f6-531a-11e8-956e-0a3cf9310a40.png)

**Comment by Zygus42** [comment]
ChopDown+Updated+(1.12.2+)-1.0.9
natura-1.12.2-4.3.2.49
Mantle-1.12-1.3.2.24

**Comment by Shovinus** [comment]
Yes, unfortunately this is because they don't actually connect to the main tree, for some reason it spawns some that are not touching the main tree sometimes so has no idea they are there.

**Comment by Zygus42** [comment]
Bummer - stoopid trees.  I have had this same problem with entire-tree chopping axes from  assorted mods in the past.  Anyway, still TONS easier than chopping the entire thing by hand - takes like a year.  

You do also unfortunately get quite a few instances where they refuse to fall over:
![2018-05-10_00 46 46](https://user-images.githubusercontent.com/20757445/39827855-cc284c5e-53eb-11e8-9789-f103497030d8.png)

**Comment by Shovinus** [comment]
There is the possibility that the block you chopped through is not on a solid block, as in the roots are over a cave? It requires the block you are chopping to be rooted below on a solid none wood block, such as dirt or stone, however where redwoods form they do so by also creating a root system of sorts, and sometimes this can go in to a cave and this be seeming to float in air to the algorithm, could solve this by adding trunk min_vertical_logs = 20 which would mean if there is at least 20 blocks in a vertical row as wood it will treat it as a tree, see the other bop tree that has the setting at 4

**Comment by Zygus42** [comment]
The roots go way down, so certainly possible to have a cave there.  I can see these darn huge trees are a big headache :)

**Comment by Zygus42** [comment]
Ok.  Much testing along the way led to this:
https://github.com/progwml6/Natura/issues/413
(my comment at the bottom).

Turns out that there's now 2 types of this tree, one with and one without blocks holding the leaves together.  If you chopdown the one without leaves you get some balls of leaves hanging in midair.  Frankly I see this as a Natura problem, not yours, as it happens no matter how you chop them down.  Hopefully they will fix this.

As to the not falling over all the time, who knows.  They mostly do fall over, so good enough :)

**Comment by Shovinus** [comment]
Natura issue, nothing I can do to fix it without creating a custom instance
